---
title: "Homework 5"
author: "Nidhi Patel"
date: "11/18/2020"
output: github_document
---
```{r}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.height = 6,
  out.width = "90%")

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_color_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1

#### Read in Data + make vars we want

```{r}
homicide = read_csv("./data/homicide-data.csv") %>% 
  unite(city_state, c("city", "state"), sep = "_") %>% 
  mutate(
    solved = ifelse(disposition == "Closed by arrest", rep(TRUE), FALSE))
```

This dataset contains `r ncol(homicide)` variables with `r nrow(homicide)` observations.  Each homicide is distinguished by an unique id, contains basic demographic information about the victim, the location and reported date of the murder, and whether an arrest was made. 

#### summarize

```{r}
prop = 
  homicide %>%
  group_by(city_state) %>% 
  summarize(
    tot_hom = n(),
    unsolved_hom = sum(solved == "FALSE")) %>% 
  filter(city_state != "Tulsa_AL")
```

#### `prop.test` proportions

```{r}
prop.test(
  prop %>% filter(city_state == "Baltimore_MD") %>% pull(unsolved_hom),
  prop %>% filter(city_state == "Baltimore_MD") %>% pull(tot_hom)
) %>% #you have to put the actual numbers in the prop test fn. 
  broom::tidy()
```

